// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTLFH-4UkTSv9jeGR3vojBfXWEmwwiUvc',
    appId: '1:328443475512:web:1ad43b60e1906d099018cd',
    messagingSenderId: '328443475512',
    projectId: 'services-7dc93',
    authDomain: 'services-7dc93.firebaseapp.com',
    storageBucket: 'services-7dc93.appspot.com',
    measurementId: 'G-RM2VMWWDVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByRPDJbxpmGvXXArjnHNPF7UldmWUAGQA',
    appId: '1:328443475512:android:10c320ce3b7d1b7a9018cd',
    messagingSenderId: '328443475512',
    projectId: 'services-7dc93',
    storageBucket: 'services-7dc93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLYXvgC_d52PeDrBWaT8ETSERYO5Dy5fw',
    appId: '1:328443475512:ios:00cbd0d50c7694939018cd',
    messagingSenderId: '328443475512',
    projectId: 'services-7dc93',
    storageBucket: 'services-7dc93.appspot.com',
    androidClientId: '328443475512-8s14h9h5nv2umi8k9akr5r41f4k0nl5p.apps.googleusercontent.com',
    iosBundleId: 'com.app.hadawiApp',
  );
}
